### PR TITLE
Generalize responsive scaffold

### PR DESCRIPTION
**Pull request by nils-ten-hoeve**
Hello Tushar.

As per request by e-mail: herby my first pull request ever :-D
Any questions are welcome.

Thanks again

Kind regards
Nils ten Hoeve

### CODE REVIEW

**Comment by tusharsadhwani** [comment]
Hey!

I'm currently on the road so I can't test the code locally, so I'll probably review this sometime tomorrow.

But, thanks for the PR! It looks like a solid start for the feature, and if things work I'd be inclined to merge it.

**Comment by tusharsadhwani** [comment]
LGTM. Sorry for a bit late review, and thanks for the PR!

**Comment by tusharsadhwani** [comment]
v1.1.0 has been published.

**Comment by nils-ten-hoeve** [comment]
Thanks!

Maybe one more suggestion for a better CHANGELOG.md

## [1.1.0] - May, 2023 (with help of Nils ten Hoeve)
- Implemented null safety
- Improved customization with more constructor parameters (almost all original Scaffold parameters can now be used):
  - Full control over AppBar widget
  - Full control over menu widget
  - Control of the menu (open/close) with help op the ResponsiveMenuController
- Implemented flutter lints 2.0.1

## [1.0.0] - July 6, 2020 by Tushar Sadhwani
- Initial Release

**Comment by tusharsadhwani** [comment]
Any changes would happen via pull request. if you think it's important enough, feel free to make one, and I'll do a review.

The updated changelog won't go into 1.1.0 i think because i can't re publish that version.

**Pull request merged**
